# -*- coding: utf-8 -*-
{
    'name': 'custom security for ktv',
    'version': '0.1',
    'category': 'Uncategorized',
    'description': """定制权限,包括角色、访问权限、菜单等""",
    'author': 'chengdh (cheng.donghui@gmail.com)',
    'website': '',
    'license': 'AGPL-3',
    'depends': [],
    'data': [
      "menu_view.xml",
      "security/custom_security.xml",
      "security/ir.model.access.csv",
      "security/ir.filters.csv",
      ],
    'demo_xml': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'web':True,
    'css': [],
    'js': [],
    'xml': [],
}
